[project]
name = "song-manager"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorlog>=6.9.0",
    "dirsync",
    "httpx>=0.28.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pydub>=0.25.1",
    "pyyaml>=6.0.2",
    "rekordbox-client",
    "song-common",
    "spotdl>=4.4.3",
    "spotify-client",
    "spotipy>=2.25.1",
    "streamlit>=1.45.0",
    "tqdm>=4.67.1",
    "xmltodict>=0.14.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "python-dotenv>=1.2.1",
    "ruff>=0.11.8",
]

[tool.uv.sources]
dirsync = { git = "https://github.com/beathvn/dirsync.git", rev = "develop" }
spotify-client = { workspace = true }
song-common = { workspace = true }
rekordbox-client = { workspace = true }

[tool.uv.workspace]
members = ["libs/spotify_client", "libs/rekordbox_client", "libs/song_common"]

[tool.ruff]
exclude = [".git", "__pycache__", ".venv"]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = "dynamic"
line-ending = "auto"
