datapath: ./data/spotify/
datapath_playlists: ./data/spotify_playlists/

playlist_to_allowed_tracks:
    37i9dQZEVXbMDoHDwVN2tF: 2    # Top 50 Globale
    4oLmXFdYv5ho24j9LEyPEN: 6    # House Nation
    0ZhTd0v0esEM40nX1S66g0: 6    # STMPD RCRDS New Releases

artists_followed: 
    - 7vk5e3vY1uw9plTHJAMwjN # Alan Walker 
    - 1yxSLGMDHlW21z4YXirZDS # Black Eyed Peas 
    - 0du5cEVh5yTK9QJze8zA0C # Bruno Mars 